name: Build Latest FEX and Wine 9.2

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'benchmarks/**'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - 'README.md'

jobs:
  foundations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [debian13, ubuntu2404]

    steps:
    - uses: actions/checkout@v1
    - name: free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        df -h

    - name: Cache docker image
      id: cache-foundation
      uses: actions/cache@v4
      env:
        cache-name: cache-foundation
      with:
        path: foundation${{ matrix.os }}.tgz
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles(format('.packaging/{0}/Dockerfile', matrix.os)) }}
        lookup-only: true

    - name: Setup packaging
      if: ${{ steps.cache-foundation.outputs.cache-hit != 'true' }}
      run: |
        cp .packaging/${{ matrix.os }}/Dockerfile .

    - name: Build package
      if: ${{ steps.cache-foundation.outputs.cache-hit != 'true' }}
      run: docker build -t foundation${{ matrix.os }} .

    - name: Export docker image
      if: ${{ steps.cache-foundation.outputs.cache-hit != 'true' }}
      run: docker image save foundation${{ matrix.os }} | gzip -c > foundation${{ matrix.os }}.tgz

  fex-latest:
    needs: foundations
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [debian13, ubuntu2404]

    steps:
    - uses: actions/checkout@v1
    - name: free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        df -h

    - name: Cache docker image
      id: cache-foundation
      uses: actions/cache@v4
      env:
        cache-name: cache-foundation
      with:
        path: foundation${{ matrix.os }}.tgz
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles(format('.packaging/{0}/Dockerfile', matrix.os)) }}

    - name: Import docker image
      run: docker image load -i foundation${{ matrix.os }}.tgz

    - name: get version
      run: git describe --tags | sed "s/hangover-/HOVERSION=/" >> "$GITHUB_ENV"; git describe --tags | sed "s/hangover-/HOVERSION=/"

    - name: Clone latest FEX
      run: |
        rm -rf fex-latest
        git clone --depth 1 --branch main https://github.com/FEX-Emu/FEX.git fex-latest

    - name: Setup FEX packaging
      run: |
        cp -r .packaging/${{ matrix.os }}/fexpe/* fex-latest
        cp fex-latest/LICENSE fex-latest/DEBIAN/copyright
        sed -i "s/HOVERSION/${HOVERSION}/g" fex-latest/Dockerfile
        sed -i "s/HOVERSION/${HOVERSION}/g" fex-latest/DEBIAN/control
        # 更新版本信息
        sed -i "s/starting FEX based/starting FEX (Hangover ${HOVERSION}) based/g" fex-latest/Source/Windows/ARM64EC/Module.cpp
        sed -i "s/starting FEX based/starting FEX (Hangover ${HOVERSION}) based/g" fex-latest/Source/Windows/WOW64/Module.cpp
        nproc

    - name: Build FEX package
      run: cd fex-latest; docker build -t fex-latest-${{ matrix.os }} .

    - name: Extract FEX package
      run: docker run --rm fex-latest-${{ matrix.os }} cat /opt/deb/hangover-libwow64fex_${{ env.HOVERSION }}_arm64.deb > hangover-libwow64fex-latest_${{ env.HOVERSION }}_${{ matrix.os }}_arm64.deb

    - name: Extract FEX dll
      run: docker run --rm fex-latest-${{ matrix.os }} cat /opt/fex/build/Bin/libwow64fex.dll > libwow64fex-latest_${{ matrix.os }}.dll

    - name: Upload FEX deb as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: hangover-libwow64fex-latest_${{ env.HOVERSION }}_${{ matrix.os }}_arm64.deb
        path: hangover-libwow64fex-latest_${{ env.HOVERSION }}_${{ matrix.os }}_arm64.deb

    - name: Upload FEX dll as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: libwow64fex-latest_${{ matrix.os }}.dll
        path: libwow64fex-latest_${{ matrix.os }}.dll

  wine-9.2:
    needs: foundations
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [debian13, ubuntu2404]
        include:
          - os: debian13
            codename: trixie
          - os: ubuntu2404
            codename: noble

    steps:
    - uses: actions/checkout@v1
    - name: free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        df -h

    - name: Cache docker image
      id: cache-foundation
      uses: actions/cache@v4
      env:
        cache-name: cache-foundation
      with:
        path: foundation${{ matrix.os }}.tgz
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles(format('.packaging/{0}/Dockerfile', matrix.os)) }}

    - name: Import docker image
      run: docker image load -i foundation${{ matrix.os }}.tgz

    - name: get version
      run: git describe --tags | sed "s/hangover-/HOVERSION=/" >> "$GITHUB_ENV"; git describe --tags | sed "s/hangover-/HOVERSION=/"

    - name: Clone Wine 9.2
      run: |
        rm -rf wine-9.2
        git clone --depth 1 --branch wine-9.2 https://github.com/wine-mirror/wine.git wine-9.2

    - name: Setup Wine 9.2 packaging
      run: |
        cp -r .packaging/${{ matrix.os }}/wine/* wine-9.2
        sed -i "s/HOVERSION/${HOVERSION}/g" wine-9.2/Dockerfile
        nproc

    - name: Adjust changelog for Wine 9.2
      if: github.event_name != 'release'
      run: |
        cp wine-9.2/debian/changelog wine-9.2/debian/changelog.old
        echo "hangover-wine-9.2 (${HOVERSION}~${{ matrix.codename }}) UNRELEASED; urgency=low" > wine-9.2/debian/changelog.entry
        echo "" >> wine-9.2/debian/changelog.entry
        echo "  * Wine 9.2 build ${HOVERSION}~${{ matrix.codename }}" >> wine-9.2/debian/changelog.entry
        echo "" >> wine-9.2/debian/changelog.entry
        echo -n " -- André Zwing <nerv@dawncrow.de>  " >> wine-9.2/debian/changelog.entry
        LC_TIME=en_US.UTF-8 date "+%a, %d %b %Y %H:%M:%S %z" >> wine-9.2/debian/changelog.entry
        echo "" >> wine-9.2/debian/changelog.entry
        cat wine-9.2/debian/changelog.entry wine-9.2/debian/changelog.old > wine-9.2/debian/changelog
        rm wine-9.2/debian/changelog.entry wine-9.2/debian/changelog.old
        cat wine-9.2/debian/changelog

    - name: Adjust changelog for Wine 9.2 release
      if: github.event_name == 'release'
      run: |
        cp wine-9.2/debian/changelog wine-9.2/debian/changelog.old
        echo "hangover-wine-9.2 (${HOVERSION}~${{ matrix.codename }}) UNRELEASED; urgency=low" > wine-9.2/debian/changelog.entry
        echo "" >> wine-9.2/debian/changelog.entry
        echo "  * Wine 9.2 Release ${HOVERSION}~${{ matrix.codename }}" >> wine-9.2/debian/changelog.entry
        echo "" >> wine-9.2/debian/changelog.entry
        echo -n " -- André Zwing <nerv@dawncrow.de>  " >> wine-9.2/debian/changelog.entry
        LC_TIME=en_US.UTF-8 date "+%a, %d %b %Y %H:%M:%S %z" >> wine-9.2/debian/changelog.entry
        echo "" >> wine-9.2/debian/changelog.entry
        cat wine-9.2/debian/changelog.entry wine-9.2/debian/changelog.old > wine-9.2/debian/changelog
        rm wine-9.2/debian/changelog.entry wine-9.2/debian/changelog.old
        cat wine-9.2/debian/changelog

    - name: Build Wine 9.2 package
      run: cd wine-9.2; docker build -t wine-9.2-${{ matrix.os }} .

    - name: Extract Wine 9.2 package
      run: docker run --rm wine-9.2-${{ matrix.os }} cat /opt/hangover-wine-9.2_${{ env.HOVERSION }}~${{ matrix.codename }}_arm64.deb > hangover-wine-9.2_${{ env.HOVERSION }}~${{ matrix.codename }}_arm64.deb

    - name: Upload Wine 9.2 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: hangover-wine-9.2_${{ env.HOVERSION }}~${{ matrix.codename }}_arm64.deb
        path: hangover-wine-9.2_${{ env.HOVERSION }}~${{ matrix.codename }}_arm64.deb

  bundle-fex-wine92:
    needs: [fex-latest, wine-9.2]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [debian13, ubuntu2404]
        include:
          - os: debian13
            codename: trixie
          - os: ubuntu2404
            codename: noble

    steps:
    - uses: actions/checkout@v1
    - name: free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        df -h

    - name: get version
      run: git describe --tags | sed "s/hangover-/HOVERSION=/" >> "$GITHUB_ENV"; git describe --tags | sed "s/hangover-/HOVERSION=/"

    - name: Download FEX Artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: hangover-libwow64fex-latest_*_${{ matrix.os }}_arm64.deb
        merge-multiple: true

    - name: Download Wine 9.2 Artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: hangover-wine-9.2_*${{ matrix.codename }}_arm64.deb
        merge-multiple: true

    - name: Create FEX + Wine 9.2 bundle
      run: |
        tar -cf hangover_fex-latest_wine-9.2_${{ env.HOVERSION }}_${{ matrix.os }}_${{ matrix.codename }}_arm64.tar \
          hangover-libwow64fex-latest_*_${{ matrix.os }}_arm64.deb \
          hangover-wine-9.2_*${{ matrix.codename }}_arm64.deb

    - name: Upload FEX+Wine9.2 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: hangover_fex-latest_wine-9.2_${{ env.HOVERSION }}_${{ matrix.os }}_${{ matrix.codename }}_arm64.tar
        path: hangover_fex-latest_wine-9.2_${{ env.HOVERSION }}_${{ matrix.os }}_${{ matrix.codename }}_arm64.tar
        retention-days: 14

    - name: Upload Artifact as Release Asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: hangover_fex-latest_wine-9.2_${{ env.HOVERSION }}_${{ matrix.os }}_${{ matrix.codename }}_arm64.tar
        asset_name: hangover_fex-latest_wine-9.2_${{ env.HOVERSION }}_${{ matrix.os }}_${{ matrix.codename }}_arm64.tar
        asset_content_type: application/x-tar